import { AuthProvider } from "@/providers/AuthProvider";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import { ChildrenProps } from "@/types/props";
import "./global.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: ChildrenProps) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Header />
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
