import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import { ChildrenProps } from "@/types/props";
import "./global.css";
import getCurrentUser from "@/app/actions/getCurrentUser";

export const metadata = {
  title: "Home | next.js realworld example app",
  description: "Generated by Next.js",
};

export default async function RootLayout({ children }: ChildrenProps) {
  const currentUser = await getCurrentUser();
  return (
    <html lang="en">
      <body>
        <Header currentUser={currentUser} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
